version: '3.10'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '6543:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
