version: '3.10'

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - ./src/.env
    ports:
      - '6543:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    networks:
      - app_network
  app:
    build: .
    volumes:
      - ./src:/src
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge