"""First migration

Revision ID: 589900d80374
Revises: 
Create Date: 2024-04-17 16:58:45.371874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589900d80374'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'customer_id')
    op.drop_column('bookings', 'spaceship_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('spaceship_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
